### ISSUE TITLE
Cannot find any of the supported PHP image extensions

### ISSUE THREAD

**Issue by pnbecker** [martialblog/docker-limesurvey#51]
Thank you for providing this image. Overall it is great!

For larger textelements of surveys or for some question types CKeditor is loaded. Within the editor, there is a button to add an image to the text. When I click on the button to add an image, an overlay opens where I can paste a URL of the image I'd like to add. Next to it is a button "Server durchsuchen" (that's German vor search within the server). If I click this, a popup opens, that shows me a text "Cannot find any of the supported PHP image extensions!". I ensured that gd is installed and activated.

I'm not sure if that is related to your docker image or if that is a bug in either limesurvey or ckeditor. Do you have any idea how to narrow this down?

**Comment by pnbecker** [comment]
The image misses the php imagick package and the debian package magicwand-dev. I was able to solve my issue by running `apt-get update && apt-get install imagemagick libmagickwand-dev  && /usr/local/php/bin/pecl install imagick && echo 'extension=imagick.so' > /usr/local/etc/php/conf.d/imagick.ini` in the container.

**Comment by martialblog** [comment]
Hi, thanks for the hint. I'll have a look at it

**Comment by martialblog** [comment]
@pnbecker Hey hey, adding the imagemagick would add an entire new image library to the image. GD is already installed, but it wasn't configured properly. 

I fixed that here: https://github.com/martialblog/docker-limesurvey/tree/fix-gd

You can test the new branch, it should work as expected. Make sure the permissions to the upload folder are correct.

I will merge this as soon as a new LS Release is out. Thanks for the bugreport! :medal_military: 

Cheers,
Markus

**Comment by martialblog** [comment]
PR was merged and new build is on its way. Should be fixed. 

Let me know if there's still an issue.

Cheers, Markus

**Comment by danielchan-bss** [comment]
Thanks Markus have a fix for this issue. 
However, I still cannot use the KCFinder. 
1. For Chrome, the website is stuck in loading when i click the "Browse Server" button. 
![image](https://user-images.githubusercontent.com/80511740/115867221-605c8a00-a46d-11eb-8192-401ff29cbc83.png)
2. For IE, I can open the KCFinder but it shows "Web page cannot be displayed" when i click the "upload" button
![image](https://user-images.githubusercontent.com/80511740/115867491-c0533080-a46d-11eb-8485-cfab892ccf52.png)

I have set the permission to upload folder by "chmod 777" already but it's same issue.
How can i solve it?
Should i need to set some volume in the docker compose file?
I have tried to fix this for a whole day but still not work. T^T

Thanks!
